[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/nightfox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14

[window]
option_as_alt = "Both"
padding.x = 4
padding.y = 4

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" }
]
