[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/nightfox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[window]
padding.x = 4
padding.y = 4
