brew "age"
brew "awscli"
brew "colima"
brew "docker"
brew "docker-compose"
brew "git"
brew "helm"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "sops"
brew "starship"

cask "alacritty", args: { no_quarantine: true }
cask "font-jetbrains-mono-nerd-font"
