format = "$character$directory$git_branch${custom.git_dirty} "

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"

[git_branch]
format = "[ git:\\([$branch](bold red)\\)](blue)"

[custom.git_dirty]
format = "[ *](bright-yellow)"
require_repo = true
when = '[[ -n "$(git status --porcelain)" ]]'
