format = "$character$directory$git_branch${custom.git_dirty} "

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"

[git_branch]
format = "[ git:\\([$branch](bold red)\\)](blue)"

[custom.git_dirty]
format = "[ $output](bright-yellow)"
require_repo = true
when = true
command = '''
if [[ -n "$(git status --porcelain)" ]]; then
  echo "*"
fi
'''
